# Generated by Django 3.0.8 on 2020-08-24 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfoUpdate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hobby', models.CharField(max_length=264)),
                ('occupation', models.CharField(max_length=264)),
                ('educational_institutions', models.CharField(max_length=264)),
                ('subject_of_study', models.CharField(max_length=264)),
                ('subject_of_level', models.CharField(choices=[('নিম্ন মাধ্যমিক', 'নিম্ন মাধ্যমিক'), ('মাধ্যমিক', 'মাধ্যমিক'), ('উচ্চ মাধ্যমিক', 'উচ্চ মাধ্যমিক'), ('স্নাতক', 'স্নাতক'), ('স্নাতকোত্তর', 'স্নাতকোত্তর'), ('এম ফিল', 'এম ফিল'), ('পিএইচডি', 'পিএইচডি')], max_length=50)),
                ('your_self', models.CharField(max_length=512)),
            ],
        ),
    ]
