# Generated by Django 3.0.8 on 2020-09-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAcount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfoupdate',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pic/', verbose_name='Upload profile picture'),
        ),
    ]
