# Generated by Django 3.0.8 on 2020-09-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAcount', '0002_userprofileinfoupdate_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfoupdate',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/', verbose_name='Upload profile picture'),
        ),
    ]
